name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: gh-deploy
        run: |
          git config --global user.name 'JeremyBot'
          git config --global user.email 'jeremysprofile@users.noreply.github.com'
          pip3 install "mkdocs==1.2.1" "jinja2==3.0.1" "pymdownx-extensions"
          mkdocs gh-deploy --force
